# Numpy

### Arrays  - Arrays are a datatype used to store similar type of data

#### Arrays can be one dimensional (vectors) or two dimensional (matrices)


In [1]:
import numpy as np

In [5]:
# One Dimensional Array

list1 = ['ai','cloud','python']
array1 = np.array(list1)
print(array1)
print(type(array1))
print(array1.shape) 
# shape tells number of rows,number of columns
# since its a one dimensional array, it shows (3,)

['ai' 'cloud' 'python']
<class 'numpy.ndarray'>
(3,)


In [12]:
# Two dimensional array
list1 = ['ai','cloud','python']
list2 = ['mech','civil','aerospace']
list3 = ['hw','quiz','assignments']
array2d = np.array([list1,list2,list3])

print(array2d)  ### 2d array represented by two square brackets
print(type(array2d))
print(array2d.shape)  # 3 rows,3 columns

[['ai' 'cloud' 'python']
 ['mech' 'civil' 'aerospace']
 ['hw' 'quiz' 'assignments']]
<class 'numpy.ndarray'>
(3, 3)


##### Indexing a 2D array

In [22]:
#first we index rows, then we index columns
print(array2d[:,:]) #all rows, all columns

print('\n')
print(array2d[1:,])# everything after1st row, all columns

print('\n')
print(array2d[1,:2])# second row, first 2 columns

print('\n')
print(array2d[:2,1])# extract cloud,civil - first 2 rows,1st column only

[['ai' 'cloud' 'python']
 ['mech' 'civil' 'aerospace']
 ['hw' 'quiz' 'assignments']]


[['mech' 'civil' 'aerospace']
 ['hw' 'quiz' 'assignments']]


['mech' 'civil']


['cloud' 'civil']


# numpy basic methods

#### arange(start,end,step) generates 1D array with equal spaced elements as provided in step

In [25]:
print(np.arange(1,15))
print(np.arange(1,15,3))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  4  7 10 13]
[1]


#### linspace - similar as arange

### arange vs linspace
- arange focus more on stepsize but linspace focuses more on creating equal spaced elements
- arange excludes end value but linspace includes end value

In [27]:
print(np.arange(1,15,50))
print('\n')
print(np.linspace(1,15,50))

[1]


[ 1.          1.28571429  1.57142857  1.85714286  2.14285714  2.42857143
  2.71428571  3.          3.28571429  3.57142857  3.85714286  4.14285714
  4.42857143  4.71428571  5.          5.28571429  5.57142857  5.85714286
  6.14285714  6.42857143  6.71428571  7.          7.28571429  7.57142857
  7.85714286  8.14285714  8.42857143  8.71428571  9.          9.28571429
  9.57142857  9.85714286 10.14285714 10.42857143 10.71428571 11.
 11.28571429 11.57142857 11.85714286 12.14285714 12.42857143 12.71428571
 13.         13.28571429 13.57142857 13.85714286 14.14285714 14.42857143
 14.71428571 15.        ]


## extracting array elements which satisfy a condition - CONDITIONAL SELECTION


In [51]:
array_var = np.array([1,2,3,4,5])
array_var[array_var<3]

array([1, 2])

#### some more numpy operations

In [74]:
#np.ones(shape,dtype)
print(np.ones((1,2),dtype = int))
print('\n')

#random distribution(shape) - random sampling using uniform distribution
print(np.random.rand(4,5))
print('\n')
 
#standard normal distribution
print(np.random.randn(4,5))
print('\n')

#randint(start,end,size,dtype) - same as random.rand but here you can define a range
print(np.random.randint(0,100,50))
print('\n')

#identity matrix
print(np.eye(3))
print('\n')


#argmax - gives position of maximum element across any axis, axis=0 means column, 1 means row. If no axis provided, looks in whole array
mat = np.random.randn(4,5)
print(mat)
print('\n')
print(mat.argmax()) #gives index of maximum element
print(mat.argmax(axis =0)) #goes to each column and returs an array of index of max element in each column



[[1 1]]


[[0.33291909 0.04996351 0.65299032 0.05787402 0.26351224]
 [0.60584896 0.83461158 0.48803644 0.2299251  0.75414946]
 [0.85841245 0.96750617 0.24065554 0.0952633  0.06361331]
 [0.8433525  0.81535499 0.44482664 0.33459571 0.05715745]]


[[ 1.00999906  0.89916483  1.40694757 -0.49785498 -0.28139001]
 [-0.24871837  1.53164909 -1.9010479   2.02483758  0.45496872]
 [-0.2750952  -0.52826634  0.63889257 -1.17309368  0.1776159 ]
 [-0.29710352 -0.13556345  0.51783455  0.87011494 -0.0955858 ]]


[13 32 18 49 56 79 17 98 17 86 88 21 68 62 26 31 64 34 62 42 24 86 73 20
  5 54  1  9 18 99  1 81  5 34 54 27 18 70 40  9 21  8 94 99 56 54 13 22
 36 61]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[ 1.2344489  -0.09495859  0.36504409 -0.74204134 -0.08630931]
 [-0.17347921 -1.16129726 -0.48730525  0.83313616 -0.22054723]
 [ 0.63611819 -0.53395916  1.21817357 -1.96508916 -1.70847142]
 [-1.13314389 -0.2373116   0.79309645  0.7372791  -0.53013127]]


0
[0 0 2 1 0]


#### OPERATIONS ON MATRICES

In [67]:

mat = np.random.rand(4,5)
print(mat)
print('\n')

print(mat.sum())
print(mat.std())

[[0.12882648 0.64014651 0.89951567 0.54601028 0.18656689]
 [0.6934266  0.50791495 0.53451036 0.04697577 0.01086553]
 [0.36770682 0.39061858 0.16559836 0.53794311 0.03926452]
 [0.3967902  0.63537374 0.77932811 0.97835412 0.34981933]]


8.835555939348891
0.2780397287893086


### Array methods


### array.reshape() 
#### The total number of items before reshape should be same as after reshape 
#### Example : 3x3 can be converted to 9x1 or 1x9

In [11]:
list1 = ['ai','cloud','python']
list2 = ['mech','civil','aerospace']
list3 = ['hw','quiz','assignments']
array2d = np.array([list1,list2,list3])

array2d.reshape(1,9)  # one row,9 columns


array([['ai', 'cloud', 'python', 'mech', 'civil', 'aerospace', 'hw',
        'quiz', 'assignments']], dtype='<U11')

### Pass by reference vs shallow copy vs deep copy
https://levelup.gitconnected.com/understanding-reference-and-copy-in-python-c681341a0cd8

#### Pass by reference

In [28]:
l1 = [1,2,3]
l2 = l1 
## pass by reference means l2 is not assigned a new memory share but l2 merely point at memory address of l1
#checking memory addresses
print(id(l1))
print(id(l2))

2304170749504
2304170749504


Both l1 and l2 share same memory address

In [29]:
l2[0] = 4
print(l2)
print(l1)

[4, 2, 3]
[4, 2, 3]


Because both l1 and l2 are pointing at same memory address, both lists get changed unintentionally

#### Shallow copy
To avoid pass by reference the solution is shallow copy where we instantiate a new memory block by creating a copy. However as the name suggests, it justs creates a copy on a surface level, i.e it cant allocate memory for a nested obejct

In [43]:
#import copy
l1 = [1,2,3]
l2 = l1.copy()
print(id(l1))
print(id(l2))

2304170824640
2304170811584


As seen both l1 and l2 have different memory addresses

In [44]:
l2[0] = 4
print(l1)
print(l2)
# Works good

[1, 2, 3]
[4, 2, 3]


But shallow copy fails on nested list

In [45]:
l1 = [1,2,[3,4]]
l2 = l1.copy()
l2[2][0] = 5
print(l1)
print(l2)

print(id(l1[2][0]))
print(id(l2[2][0]))
# For nested item, it still assigns same memory address. Solution is to use deep copy

[1, 2, [5, 4]]
[1, 2, [5, 4]]
140731821471648
140731821471648


#### Deep copy

In [49]:
import copy
l1 = [1,2,[3,4]]
l2 = copy.deepcopy(l1)
l2[2][0] = 5
print(l1)
print(l2)

print(id(l1[2][0]))
print(id(l2[2][0]))
# deep copy gives different addresses to nested objects as well

[1, 2, [3, 4]]
[1, 2, [5, 4]]
140731821471584
140731821471648


# Pandas library

In [75]:
import pandas as pd

# Series vs Arrays

#### Arrays can only have numerical indices and can be sliced only by numbers whereas series can have alphabetical indices

### creating series : from lists, from arrays, from dictionaries
pd.Series( data, index = [])
Here data needs to be 1 dimensional 
- No columns as parameter like data frame

In [114]:
# creating series from list
index = ['R1','R2','R3']
pd.Series([1,2,3],index)

R1    1
R2    2
R3    3
dtype: int64

In [116]:
# creating series from array
arr = np.array([1,2,3])
pd.Series(arr,['R1','R2','R3'])

R1    1
R2    2
R3    3
dtype: int32

In [119]:
# creating series from dictionary
dict_var = {'ai':1,'cloud':2,'stats':3}
series_var = pd.Series(dict_var)
print(series_var)
#This makes keys as index and values as data

ai       1
cloud    2
stats    3
dtype: int64


##### getting index and values

In [122]:
print(series_var.index)
print(series_var.values)

Index(['ai', 'cloud', 'stats'], dtype='object')
[1 2 3]


## Dataframes
- df = pd.DataFrame(data, index = [], columns=[])
- data needs to be 2 dimensional like excel
- index should contain index names, columns should contain column names

In [78]:
df = pd.DataFrame(np.arange(1,26).reshape(5,5), index = ['R1','R2','R3','R4','R5'], columns = ['C1','C2','C3','C4','C5'])
df

C1  C2  C3  C4  C5
R1   1   2   3   4   5
R2   6   7   8   9  10
R3  11  12  13  14  15
R4  16  17  18  19  20
R5  21  22  23  24  25

## Indexing a dataframe using loc, iloc, column names

#### loc just does indexing via index names whereas iloc does indexing based on index as well as column names position

In [86]:
#You can give range of index names
df = pd.DataFrame(np.arange(1,26).reshape(5,5), index = ['R1','R2','R3','R4','R5'], columns = ['C1','C2','C3','C4','C5'])
df.loc['R1':'R2']
# Gives a series output

C1  C2  C3  C4  C5
R1   1   2   3   4   5
R2   6   7   8   9  10

In [93]:
#You can give range of rows and columns
df = pd.DataFrame(np.arange(1,26).reshape(5,5), index = ['R1','R2','R3','R4','R5'], columns = ['C1','C2','C3','C4','C5'])
df.iloc[0:3,0:2]
#gives dataframe as output in this case

C1  C2
R1   1   2
R2   6   7
R3  11  12

#### Anything with one column is a series. More than one is a dataframe

In [99]:
df = pd.DataFrame(np.arange(1,26).reshape(5,5), index = ['R1','R2','R3','R4','R5'], columns = ['C1','C2','C3','C4','C5'])
df.iloc[0:3,0]
# Since there is only one column here this is a series

R1     1
R2     6
R3    11
Name: C1, dtype: int32

### indexing using column names

In [128]:
df = pd.DataFrame(np.arange(1,26).reshape(5,5), index = ['R1','R2','R3','R4','R5'], columns = ['C1','C2','C3','C4','C5'])
df[['C1','C2']]

C1  C2
R1   1   2
R2   6   7
R3  11  12
R4  16  17
R5  21  22

In [131]:
df = pd.DataFrame(np.arange(1,26).reshape(5,5), index = ['R1','R2','R3','R4','R5'], columns = ['C1','C2','C3','C4','C5'])
df[df['C1']>7]

C1  C2  C3  C4  C5
R3  11  12  13  14  15
R4  16  17  18  19  20
R5  21  22  23  24  25

### converting df into arrays using .values. It removes index names and column names, just yields the data

In [101]:
df.values

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Dataframe operations

In [104]:
df.isnull().sum()
# gives a count of how many null values are present in each column

C1    0
C2    0
C3    0
C4    0
C5    0
dtype: int64

- Value counts - gives a count of unique observations in a column

In [109]:
df['C1'].value_counts()

6     1
21    1
11    1
1     1
16    1
Name: C1, dtype: int64

#### unique - gives an array of all unique values in that series

In [111]:
df['C1'].unique()

array([ 1,  6, 11, 16, 21])

In [123]:
df = pd.read_csv('Salaries.csv')
df

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [125]:
df.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

In [151]:
df.dtypes

Id                    int64
EmployeeName         object
JobTitle             object
BasePay             float64
OvertimePay         float64
OtherPay            float64
Benefits            float64
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status              float64
dtype: object

# File reading in Python

### read_csv() parameters

In [133]:
df = pd.read_csv('Salaries.csv')

In [134]:
df

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

### usecols - to read only  a set of columns

In [138]:
df_specific = pd.read_csv('Salaries.csv',usecols = ['BasePay','TotalPay'])
df_specific

BasePay   TotalPay
0       167411.18  567595.43
1       155966.02  538909.28
2       212739.13  335279.91
3        77916.00  332343.61
4       134401.60  326373.19
...           ...        ...
148649       0.00       0.00
148650        NaN       0.00
148651        NaN       0.00
148652        NaN       0.00
148653       0.00    -618.13

[148654 rows x 2 columns]

### dtype - if you want to read all your data in a specific datatype format use this. By deafult, dtype = None. 
But if i want all my data in string format 

In [142]:
df_specific = pd.read_csv('Salaries.csv',usecols = ['BasePay','TotalPay'], dtype=object)
df_specific.loc[1]['BasePay']
#Its a string

'155966.02'

- To read different columns as different datatype, provide a dict of formats in dtype

In [150]:
df_specific = pd.read_csv('Salaries.csv',usecols = ['BasePay','TotalPay'], dtype={'BasePay':str,'TotalPay':np.float})
print(type(df_specific.iloc[0,0]))
print(type(df_specific.iloc[0,1]))

<class 'str'>
<class 'numpy.float64'>


### index_col - make a specific column as an index

In [158]:
df_specific = pd.read_csv('Salaries.csv',index_col = 0) #make id column as my index
print(df_specific.columns)
print('\n')
print(df_specific)


Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')


             EmployeeName                                        JobTitle  \
Id                                                                          
1          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
2            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
3          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
4       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
5         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148650      Roy I Tillery                                       Custodian   
148651       Not provided                                    Not provided   
148652       Not provided            

### Sometimes pandas automatically takes 1st column as index sometimes. Use index_col = false to avoid that

In [160]:
df_specific = pd.read_csv('Salaries.csv',index_col = False)
df_specific
#This automatically makes index as 0,1,2...

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

### header = None 
Header decides which row info to use as column names
Puts column names as 0,1,2...

### Python JSON

### Reading a json
df = pd.read_json(jsonfilename)
### Writing a df to a json format
df.to_json(orient = index/records)


### Reading webpage - pd.read_html(url,match)
This reads tables of a webpage and returns lsit of tables
match helps you identify which table to pick out of all the tables

### Reading excel
pd.read_excel('filename.xlsx')